### ISSUE TITLE
Relevance-based Word Embedding

### ISSUE THREAD

**Issue by hamed-zamani** [teinhonglo/Information-retrieval#1]
Hi,

I've noticed that you have an implementation of relevance-based word embedding in this repo. Is this the implementation of the following paper?
https://dl.acm.org/citation.cfm?doid=3077136.3080831

Best,
Hamed Zamani
zamani@cs.umass.edu

**Comment by teinhonglo** [comment]
This is refer the first method (Relevance Likelihood Maximization Model) in the paper.

In my understanding:
Input is original BOW representation, which feed into feedforward neural network, then output is reformulated representation with other Pseudo Relevance feedback.

Best,
Tien-Hong, Lo

**Comment by hamed-zamani** [comment]
Thanks for the response. Have you tested it? Are the quality of embeddings better than word2vec? Are you sure that the implementation is correct?

I am asking these questions, because people reach me regarding this paper and I would like to point them to your repo, if you have tested it and you're sure that the implementation is correct.

Thanks,
Hamed
