### ISSUE TITLE
background confuses me a lot

### ISSUE THREAD

**Issue by xiaokongkong** [teinhonglo/Information-retrieval#10]
Where is the file named "XIN1998.18461.wid.n1.lm.wid" in /Corpus/background from?
What's the relationship between background and query_model or doc_model?

**Comment by teinhonglo** [comment]
1. A file "XIN1998.18461.wid.n1.lm.wid" is generated by counting word frequency in collection.
2.  A background model is a smoothing model between queries and documents.
