### ISSUE TITLE
What papers are these based on?

### ISSUE THREAD

**Issue by lambdaofgod** [teinhonglo/Information-retrieval#14]
Could you please provide brief description what you were implementing?

For some folders it's easy to find corresponding papers on arXiv, but for others, like for example for `Query-Likelihood-Retrieval-Model` I couldn't find it.

**Comment by teinhonglo** [comment]
Sure.
The reference of QL model is in wiki ([https://en.wikipedia.org/wiki/Query_likelihood_model](https://en.wikipedia.org/wiki/Query_likelihood_model))
